### ISSUE TITLE
Error when trying to trade "No"

### ISSUE THREAD

**Issue by nielstron** [manifoldmarkets/manifold#2847]
I am a new user, never bought mana but received some as rewards.  I recently tried to trade 50/200 Mana for "No" on some market and got this error message:
```
error: null value in column "data" of relation "users" violates not-null constraint at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98) at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29) at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38) at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42) at Socket.emit (node:events:513:28) at addChunk (node:internal/streams/readable:324:12) at readableAddChunk (node:internal/streams/readable:297:9) at Readable.push (node:internal/streams/readable:234:10) at TCP.onStreamRead (node:internal/stream_base_commons:190:23) at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
```

**Comment by u66u** [comment]
Same here
